title: My First Blog and template!
author: Jan Sunshine53
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
"Welcome to the Sunshine53's homepage!"
Feel free to bookmark this page to keep an eye on my project updates.
I will be adding new information weekly.
Some Favorite Links
https://www.w3.org/2002/03/tutorials.html#w3c_all
# social links
twitter_username: your-twitter-handle
github_username:  sunshine53

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day